version: '2'
services:
  gateway:
    build: gateway
    ports:
      - "8000:8000"
    hostname: "kaazing.example.com"
    environment: 
      GATEWAY_OPTS: -Dfeature.redis=true
  redis:
    image: redis:latest
